basePath: /
definitions:
  handler.Message:
    properties:
      message:
        type: string
    type: object
  handler.ResponseId:
    properties:
      id:
        type: integer
    type: object
  modul.Account:
    properties:
      balance:
        type: number
      created_at:
        type: string
      currency:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      is_locked:
        type: boolean
    type: object
  modul.Transactions:
    properties:
      account_id:
        type: integer
      amount:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      transaction_type:
        type: string
    type: object
host: localhost:2006
info:
  contact: {}
  description: API Server for TodoList Application
  title: Todo App API
  version: "1.0"
paths:
  /api/accounts:
    get:
      consumes:
      - application/json
      description: Get a list of all accounts
      operationId: get-account-all
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modul.Account'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Get All Accounts
      tags:
      - api
    post:
      consumes:
      - application/json
      description: Create a new account
      operationId: create-account
      parameters:
      - description: Account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modul.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Create Account
      tags:
      - api
  /api/accounts/{account_id}:
    delete:
      consumes:
      - application/json
      description: Delete an account by ID
      operationId: delete-account-by-id
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Delete Account
      tags:
      - api
    get:
      consumes:
      - application/json
      description: Get account details by ID
      operationId: get-account-by-id
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modul.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Get Account
      tags:
      - api
  /api/accounts/{account_id}/deposit:
    post:
      consumes:
      - application/json
      description: Deposit money into an account
      operationId: deposit-money
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      - description: Deposit Details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modul.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Deposit BALANCE
      tags:
      - Transactions
  /api/accounts/{account_id}/transactions:
    get:
      consumes:
      - application/json
      description: Get transaction history of an account
      operationId: get-transaction-history
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modul.Transactions'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Get Transactions
      tags:
      - Transactions
  /api/accounts/{account_id}/transfer:
    post:
      consumes:
      - application/json
      description: Transfer money between accounts
      operationId: transfer-money
      parameters:
      - description: Sender Account ID
        in: path
        name: account_id
        required: true
        type: integer
      - description: Transfer Details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modul.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Transfer Balance
      tags:
      - Transactions
swagger: "2.0"
